### ISSUE TITLE
Car Speed on HUD

### ISSUE THREAD

**Issue by tugapower0** [Xxpromw3mtxX/cosmo_hud#11]
The speed that show its kinda going up and down on increments of numbers and not smooth going up and down, its like its counting in 10 and not 1 . Hope you understand what trying to say

**Comment by tugapower0** [comment]
This is because of Citizen.Wait(Config.TickTime) being the TickTime setup to 1000 on config, reducing this to 100 fix the speed being more real and not going on in incrementes of 10 more or less, but make the map on hud flick alot, maybe moving the speed to a separated thread ?

**Comment by Ramiffy** [comment]
![image](https://user-images.githubusercontent.com/66501317/147840663-271a6d14-90b0-4ffc-9f39-2e1fbe9eda00.png)

Minimap doesn't work, looks like it would be too far to the left if it did, Health bar not showing up?

**Comment by Xxpromw3mtxX** [comment]
Ehi! So I’ve moved the SpeedO module and now the speed is way better. If you’d like to give it a try, the released one is updated. Lemme know!
