### ISSUE TITLE
esx_fuel

### ISSUE THREAD

**Issue by MaccaMishima** [Xxpromw3mtxX/cosmo_hud#12]
I know majority of the people use LegacyFuel

There is still ALOT of cities that use esx_fuel to use the gas station jobs etc...

Is there anyway to update the cosmo_hud to support esx_fuel aswell? rather than just LegacyFuel?

If so, that would be awesome. More people would be able to use the HUD.

**Comment by Xxpromw3mtxX** [comment]
I'm thinking of swithcing to ox_fuel someday

**Comment by Xxpromw3mtxX** [comment]
I've not tested it, but using ox_fuel and setting showfuel to true, it should work. 
**Not gonna support esx_fuel.**
