### ISSUE TITLE
Swap mini-map not working on 1.2.1

### ISSUE THREAD

**Issue by Mr-crazey** [Xxpromw3mtxX/cosmo_hud#19]
Fresh download of 1.2.1, verified that the changes in client/main.lua are present.  Players still have the large minimap when in a vehicle.  Restarting the resource will solve the issue for players currently in the server, but not for any players that join after restart.

**Comment by robert4049** [comment]
Same issue

**Comment by Xxpromw3mtxX** [comment]
I've swapped back the minimap and now the function should work.
