### ISSUE TITLE
Status not updating

### ISSUE THREAD

**Issue by fatherandy** [Xxpromw3mtxX/cosmo_hud#2]
My hunger and thirst are not refreshing. They are showing full and not depleting.

**Comment by Xxpromw3mtxX** [comment]
Have you changed the onTick function in esx_basicneeds?
Which version are you using?

**Comment by Xxpromw3mtxX** [comment]
> My hunger and thirst are not refreshing. They are showing full and not depleting.

Did you managed to solve the problem? 
If not lemme know!

**Comment by arctikh** [comment]
Hi, same goes for me, but also for the health bar too, I am certain I followed all the steps, and sorry for bothering, just new on learning to read code and liked this hud a lot!

**Comment by arctikh** [comment]
That is, when using the original cosmo_hud, your release of cosmo_hud works perfectly fine! Sorry for reopening a closed issue, and thank you for your time fixing the script back to normal!

**Comment by Xxpromw3mtxX** [comment]
> That is, when using the original cosmo_hud, your release of cosmo_hud works perfectly fine! Sorry for reopening a closed issue, and thank you for your time fixing the script back to normal!

No worries! ;)
