### ISSUE TITLE
Fuel Indicator

### ISSUE THREAD

**Issue by arctikh** [Xxpromw3mtxX/cosmo_hud#3]
Hi, any way we can get Fuel Indicator Running?
Example pic for how it looks like atm:

![image](https://user-images.githubusercontent.com/87396862/125561328-0206dfa1-ac38-45e1-bd05-051a552a059d.png)

I have tried messing around with the code but it just makes things worse (gets rid of the ID icon with the Stress Icon even though I have it disabled on the config file)
I am quite new to this, so the best thing I did was after I tried understanding the whole thing (which I didn't) was I drag and dropped the "original" cosmo_hud html files in your release, and I made everything worse, no worries I always have a backup , but I am really trying to get FuelIndicator working.
I am using LegacyFuel so that already put line of yours really helped out, just no HUD for it

Much appreciated for reading this! Hope this helps me out!

**Comment by Xxpromw3mtxX** [comment]
In order to show the indicator you need to create a new icon inside the html as a div element, then add it in the javascript file and config everything with the right server calls using the nui callbacks.

**Comment by Xxpromw3mtxX** [comment]
And you need to create the class element too in the css for the position and dimensions.

**Comment by arctikh** [comment]
Ok, I have done what you've told me about and it looks like this now 
![image](https://user-images.githubusercontent.com/87396862/125586929-87433327-5b71-4c9d-94c8-897bd73fe4b7.png)

and to show the code: 
![image](https://user-images.githubusercontent.com/87396862/125586969-abe36c18-7c13-406c-bc16-9b8e14b0f4cd.png)
![image](https://user-images.githubusercontent.com/87396862/125587024-15f4ec6a-fcf0-4ac2-a638-f3d0e0f6318d.png)
![image](https://user-images.githubusercontent.com/87396862/125587065-01d7dbc5-22d7-4690-9404-790b3859fe35.png)
![image](https://user-images.githubusercontent.com/87396862/125587091-dd962593-1173-4774-9a81-218fa9511c2c.png)

even added it on client.lua to be sure
![image](https://user-images.githubusercontent.com/87396862/125587462-389c77e3-6997-4394-88cb-8fa5b47e71f4.png)


Thank you for helping me out, I am really certain we are close to this indicator showing up correctly

**Comment by arctikh** [comment]
To explain myself better, the fuel indicator appeared, just the bar that shows the fuel doesn't exist at all, tried many things. Also changed the following code since it was wrong, with no effect though:
local fuellevel = GetVehicleFuelLevel(veh)
to
local fuellevel = exports["LegacyFuel"]:GetFuel(veh)

and all Config.ShowFuel to Config['ShowFuel']

**Comment by Xxpromw3mtxX** [comment]
Nice! I feel like you're missing the part where you animate it.
I'll explaing my self.
Inside this function:
`if (finalfuel > 0.9) { *.animate(*); }`
nothing catches the animation.
You should try to remove the 0.2 declaration and move the path.setattribute underneath the animation.
It should be something like that:
`if (finalfuel > 0.9) { *.animate(*); *.path.setAttribute(*);}`
Maybe you could even change the if condition with:
`if (finalfuel > 0.2 && finalfuel < 'value you choose') else {[condition]}`

**Comment by Xxpromw3mtxX** [comment]
I feel like that you don't need two if condition, one for the animation and one for the setattribute.
Let me know!

**Comment by arctikh** [comment]
I think I did an ok job rewriting that part, but I don't see any progress, I am really thinking that it's somewhere else

![image](https://user-images.githubusercontent.com/87396862/125610273-abfb1ef0-59ed-4f0d-82cc-bea9decf2b64.png)
![image](https://user-images.githubusercontent.com/87396862/125610349-4878af34-dd72-47f9-9619-b4b52960eab5.png)

**Comment by Xxpromw3mtxX** [comment]
Maybe it could be a problem in the client file, go for a print of what the two values about car and fuel returns

**Comment by Xxpromw3mtxX** [comment]
or it could be that you included the fuel icon inside the div of the speedometer.

**Comment by Xxpromw3mtxX** [comment]
for the rewrite, that's exactly how I tought it

**Comment by Xxpromw3mtxX** [comment]
I was checking logic and everything while reading, and I don't see any error in this.
It should work since everything is wrote correctly.
Now as I said we need to understand if every value that we get and pass, is passed and, if it is, it is done correctly.
I would check the values about fuel and vehicle with a print(), that gives you the output inside the console.
If every value got by the fivem functions is ok and is passed correctly, you could check if the values that are passed to the js are ok using the console, then we need to understand why the progressbar is not registering it.

**Comment by arctikh** [comment]
I've been honestly on this for so long, not really sure what's the issue here

**Comment by arctikh** [comment]
I can't believe it, it actually came to a happy end.
I changed, again , the following to get the fuel indicator working:
![image](https://user-images.githubusercontent.com/87396862/125704996-a0e3b4d1-5beb-4c3f-9c46-480b1b69adfa.png)
![image](https://user-images.githubusercontent.com/87396862/125705066-0e1c6908-fa6c-49bb-8c2f-b09a1c511a89.png)
![image](https://user-images.githubusercontent.com/87396862/125705185-be927022-bbad-4650-8238-f90df2f7ee56.png)


if u want the fuel indicator to show and want the updated code tell me so I can try to send the whole thing ( I have no clue how to do that lol)

Thank you very much for your continued support and hoping the best for you my friend!

**Comment by Xxpromw3mtxX** [comment]
Probably it could've been the color since the start XD
