### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by mifsopo** [Xxpromw3mtxX/cosmo_hud#4]
hello, ive tried installing this on my own for a good couple days, give up and come back and keep having problems,. for one there is no `92          TriggerEvent('esx_status:onTick', data)` in my esx_status/client.main and theres also no option to set to false in my esx_status config closet thing to line 92 ive found is this `TriggerServerEvent('esx_status:update', GetStatusData(true))` theres also no cinfig.display in my basicneeds.config either

at the same time i dont have the actual esx versions because as of now their entire github is hidden

yeah ive even checked my old fivem servers all the way back from mid 2020 and they all say getstatusdata , none say ontick, data

**Comment by Xxpromw3mtxX** [comment]
it could be and old version of esx_status and basicneeds

**Comment by mifsopo** [comment]
somehow i got it to work, i dont know how but i just starting grabbing all the versions people had posted on the forums and one of them worked
