### ISSUE TITLE
Richiesta esx_basicneeds e esx_status

### ISSUE THREAD

**Issue by wolvherin78** [Xxpromw3mtxX/cosmo_hud#6]
Ciao, se provo a modificare la riga di codice in esx_status: 
--TriggerEvent('esx_status:onTick', data)
TriggerEvent('cosmo_hud:onTick', data),

esx_status non si avvia più, potresti in qualche modo caricare l'esx_status e il esx_basicneeds che utilizzi già aggiornati?

la stamina non funziona, se corro la stamina non scende, la vita e l'armor non appaiono

**Comment by Xxpromw3mtxX** [comment]
Ti allego la mia cartella del plugin dello stato. Prova e fammi sapere.
Prima di fare copia e incolla, fai un backup della tua.
[esx_status](https://we.tl/t-1NfY0aKK7P) <-- Questo link scade tra una settimana!

**Comment by wolvherin78** [comment]
non va, da errore esx_status/server/mail.lua:39 global 'esx' e esx_status/client/main.lua:184 global 'esx'

**Comment by Xxpromw3mtxX** [comment]
che versione di esx stai usando?

**Comment by Xxpromw3mtxX** [comment]
anche se dovrei controllare cosa c’è in quelle righe

**Comment by wolvherin78** [comment]
> che versione di esx stai usando?

da dove lo capisco?

**Comment by Xxpromw3mtxX** [comment]
puoi aprire il manifest oppure dal txadmin nella sezione risorse se cerchi es_extended

**Comment by wolvherin78** [comment]
extendedmode 1.0.1

**Comment by Xxpromw3mtxX** [comment]
trovato il problema, senza il framework esx non funzionerà.
tutti questi script si basano su esx e senza es_extended non funzionano

**Comment by wolvherin78** [comment]
ok, allora mi devo ricreare la base su es_extended, quale versione?

**Comment by Xxpromw3mtxX** [comment]
Se hai bisogno il framework ESX, completo, lo trovi [qui](https://github.com/esx-framework/esx-legacy). Al massimo crea un altro server e testalo prima, impostalo bene e poi una volta fatto importi il resto dei plugin. Ovviamente non scartare mai il tuo lavoro!

**Comment by wolvherin78** [comment]
ok, grazie

**Comment by Xxpromw3mtxX** [comment]
di nulla! chiudo l’issue.
nel caso tu avessi bisogno riaprilo!

**Comment by wolvherin78** [comment]
Ok, adesso il cibo e la seta funziona, ma non esce il simbolo della vita, dell'armor e non funziona la stamina
