### ISSUE TITLE
Vita, armor e stamina

### ISSUE THREAD

**Issue by wolvherin78** [Xxpromw3mtxX/cosmo_hud#7]
Dopo aver aggiornato l'esx il cibo e la sete funzionano, ma continua a non apparire il simbolo della vita, dell'armor e non funziona la stamina, se corro non si abbassa il simbolo o2

**Comment by Xxpromw3mtxX** [comment]
Allora la vita comincia a vedersi in automatico quando diventa < 100, l'armor quando la euquipaggi e quindi diventa > 0. Per la stamina mi sembra molto strano, stai usando l'ultima ultima?

**Comment by wolvherin78** [comment]
hai pubblicato più release?, io ne vedo solo una

**Comment by wolvherin78** [comment]
> Per la stamina mi sembra molto strano, stai usando l'ultima ultima?

C'è una release della stamina?

**Comment by Xxpromw3mtxX** [comment]
Non devi scaricare la versione della release, devi scaricare la versione dal master

**Comment by wolvherin78** [comment]
ho l'ultima versione della master scaricata da questo link https://github.com/Xxpromw3mtxX/cosmo_hud.git, ma la stamina non funziona

**Comment by wolvherin78** [comment]
Per far funzionare la stamina bisogna avere qualche altra cosa?

**Comment by Xxpromw3mtxX** [comment]
No, la stamina funziona a prescindere

**Comment by wolvherin78** [comment]
La stamina non mi ha mai funzionato, sai quale potrebbe essere il problema?

**Comment by kevinramadhan-29** [comment]
perché quando cerco la riga 92 in esx il mio stato non è presente e quando voglio scaricare esx_status mi dai 404 nout trovato e basicneeds

**Comment by wolvherin78** [comment]
@kevinramadhan-29 non ho capito la risposta

**Comment by Xxpromw3mtxX** [comment]
> La stamina non mi ha mai funzionato, sai quale potrebbe essere il problema?

Mi sembra strano perchè è gestita da una funzione di fivem e non da uno script

**Comment by Xxpromw3mtxX** [comment]
> perché quando cerco la riga 92 in esx il mio stato non è presente e quando voglio scaricare esx_status mi dai 404 nout trovato e basicneeds

Non ho capito cosa intendi dire.
Per scaricare il framework di esx devi andare [qui](https://github.com/esx-framework/esx-legacy)

**Comment by wolvherin78** [comment]
> > La stamina non mi ha mai funzionato, sai quale potrebbe essere il problema?
> 
> Mi sembra strano perchè è gestita da una funzione di fivem e non da uno script

Che versione hai dell'FXServer?
Può essere dovuto dal fatto che ho il server in locale?

**Comment by kevinramadhan-29** [comment]
l'ultimo

Pada tanggal Sel, 7 Sep 2021 pukul 14.42 wolvherin78 <
***@***.***> menulis:

**Comment by Xxpromw3mtxX** [comment]
> > > La stamina non mi ha mai funzionato, sai quale potrebbe essere il problema?
> > 
> > 
> > Mi sembra strano perchè è gestita da una funzione di fivem e non da uno script
> 
> Che versione hai dell'FXServer?
> Può essere dovuto dal fatto che ho il server in locale?

Nop, la versione del server non è importante

**Comment by wolvherin78** [comment]
Ho risolto il problema della stamina, grazie!

**Comment by Xxpromw3mtxX** [comment]
Cosa impediva il corretto funzionamento?

**Comment by wolvherin78** [comment]
un opzione sul vmenu

**Comment by kevinramadhan-29** [comment]
fondamentalmente l'hud non funziona sul mio server. Non so cosa fare
